CREATE TABLE IF NOT EXISTS Realisateur(id INT primary key auto_increment, nom VARCHAR(100), prenom VARCHAR(100), date_naissance TIMESTAMP, celebre BOOLEAN);
INSERT INTO Realisateur(nom, prenom, date_naissance, celebre) VALUES('Cameron', 'James', '1954-08-16', false);
INSERT INTO Realisateur(nom, prenom, date_naissance, celebre) VALUES('Jackson', 'Peter', '1961-10-31', true);
INSERT INTO Realisateur(nom, prenom, date_naissance, celebre) VALUES('Spielberg', 'Steven', '1946-12-18', true);
INSERT INTO Realisateur(nom, prenom, date_naissance, celebre) VALUES('Nolan', 'Christopher', '1970-07-30', true);
INSERT INTO Realisateur(nom, prenom, date_naissance, celebre) VALUES('Tarantino', 'Quentin', '1963-03-27', true);
INSERT INTO Realisateur(nom, prenom, date_naissance, celebre) VALUES('Scorsese', 'Martin', '1942-11-17', true);

CREATE TABLE IF NOT EXISTS Film(id INT primary key auto_increment, titre VARCHAR(100), duree INT, realisateur_id INT, date_sortie DATE, poster_url VARCHAR(500), date_ajout TIMESTAMP);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('avatar', 162, 1);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('La communauté de l''anneau', 178, 2);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Les deux tours', 179, 2);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Le retour du roi', 201, 2);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('king kong', 187, 2);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Le hobbit : un voyage inattendu', 169, 2);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Le hobbit : la désolation de Smaug', 161, 2);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Le hobbit : la bataille des cinq armées', 144, 2);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Jurassic Park', 127, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('E.T. l''extra-terrestre', 115, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Inception', 148, 4);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Django Unchained', 165, 5);  
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Les huit salopards', 167, 5);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Le loup de Wall Street', 180, 6);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Shutter Island', 138, 6);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Taxi Driver', 114, 6);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Les infiltrés', 151, 6);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Casino', 178, 6);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Raging Bull', 129, 6);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Goodfellas', 146, 6);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('The Departed', 151, 6);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('The Irishman', 209, 6);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Catch Me If You Can', 141, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Saving Private Ryan', 169, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Minority Report', 145, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('War of the Worlds', 116, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Lincoln', 150, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Extreme Measures', 115, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('A.I. Artificial Intelligence', 146, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Munich', 164, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('The Terminal', 128, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Close Encounters of the Third Kind', 135, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Indiana Jones and the Raiders of the Lost Ark', 115, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Indiana Jones and the Temple of Doom', 118, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Indiana Jones and the Last Crusade', 127, 3);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Eternal Sunshine of the Spotless Mind', 108, 4);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Memento', 113, 4);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('The Dark Knight', 152, 4);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Interstellar', 169, 4);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Dunkirk', 106, 4);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Inglourious Basterds', 153, 5);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Pulp Fiction', 154, 5);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Kill Bill: Volume 1', 111, 5);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Kill Bill: Volume 2', 137, 5);
INSERT INTO Film(titre, duree, realisateur_id) VALUES('Once Upon a Time in Hollywood', 161, 5);
